<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-V4VMHNU" failures="1" tests="5" name="Personal Loan" time="0.035" errors="0" timestamp="2024-05-17T10:44:38 CEST">
  <testcase classname="testng.day1" name="Demo" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.day1.Demo(day1.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="testng.day2" name="ploan" time="0.0"/>
  <testcase classname="testng.day4" name="LogInAPIHomeLoan" time="0.001"/>
  <testcase classname="testng.day4" name="MobileLoginHome" time="0.001"/>
  <testcase classname="testng.day4" name="WebLoginHome" time="0.001"/>
  <testcase classname="testng.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
